<option value="0">Static</option>
<option value="1">General</option>
<option value="2">Money</option>
<option value="3">Potion</option>
<option value="4">Teleport</option>
<option value="5">Transformation</option>
<option value="6">EXP Reward</option>
<option value="7">Skill Book</option>
<option value="8">Reserved</option>
<option value="9">Key</option>
<option value="10">Weapon</option>
<option value="11">Shield</option>
<option value="12">Clothing</option>
<option value="13">Hat</option>
<option value="14">Boots</option>
<option value="15">Gloves</option>
<option value="16">Accessory</option>
<option value="17">Belt</option>
<option value="18">Necklace</option>
<option value="19">Ring</option>
<option value="20">Bracelet</option>
<option value="21">Bracer</option>
<option value="22">Costume</option>
<option value="23">Costume Hat</option>
<option value="24">Wings</option>
<option value="25">Buddy</option>
<option value="26">Buddy 2</option>
<option value="27">Torch</option>
<option value="28">Beverage</option>
<option value="29">Effect</option>
<option value="30">Hairdye</option>
<option value="31">Hairtool</option>
<option value="32">Cure</option>
<option value="33">Title</option>
<option value="34">Visual Document</option>
<option value="35">Audio Document</option>
<option value="36">Transport Ticket</option>
<option value="37">Fireworks</option>
<option value="38">Explosive</option>
<option value="39">Buff</option>
<option value="40">Debuff</option>
